### ISSUE TITLE
Remove Google map from home page

### ISSUE THREAD

**Issue by riverspirit** [MozillaKerala/Home#27]
There is a map in the home page showing KITZ. It doesn't serve any MozK related purpose, so remove it.

**Comment by syam3526** [comment]
venue for regional sprint

**Comment by riverspirit** [comment]
Shouldn't it be in the event page? How can someone visiting the home page understand whether the map is for an event or for a Mozilla Kerala office or something?

**Comment by syam3526** [comment]
removed the map from home page.
closing the issue.

**Comment by shinenelson** [comment]
It would be good if an issue is mentioned somewhere in the activity closing rather simply closing it.

The most ideal place to do it is to mention it in the commit message itself; e.g., "_remove map directions to KITZ from home page (resolves issue #27)_".

This would provide a reference link in this issue and automatically closes this issue as soon as the commit is merged into the main branch (i.e., `master`).

Another position would be to mention the issue in the pull request that requests the change to be merged in. Again, this would provide a ping-back to the issue and close it upon merge.

This makes github flow more easier to track and understand. That's the whole point of collaboration.

**Comment by syam3526** [comment]
Thank you for that. will keep that in mind in the future.
 @shinenelson
  Can you outline the portal project idea when you are free to the group in telegram.  @yadev64 is working on the initial  design . but need your input on the general outline.
