### ISSUE TITLE
Remove Slack link from menu

### ISSUE THREAD

**Issue by riverspirit** [MozillaKerala/Home#28]
There is a link to "Slack Workspace" from the menu. We should replace it to link to a 'Get Involved' page or section that lists all the various ways in with people can get connected with the community - IRC, Telegram, Discourse, Slack, Facebook Group/page etc. Doesn't make any sense to promote Slack as a first choice.

**Comment by syam3526** [comment]
will create such a page now..

**Comment by riverspirit** [comment]
Umm, you don't have to fix everything now. I'm just creating issues to keep track of them.

**Comment by syam3526** [comment]
ok

**Comment by syam3526** [comment]
removed and added to footer along with discourse and telagram link. 
irc link already present in contact us.
